---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: take-snapshot
spec:
  schedule: "*/5 * * * *"
  suspend: false
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron
            image: emwalker/digraph-cron:v54
            args:
            - /bin/sh
            - -c
            - /opt/cron
            envFrom:
            - secretRef:
                name: digraph-secrets
          restartPolicy: Never
