---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend-ingress
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   certmanager.k8s.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
  # - hosts:
  #   - digraph.app
  #   secretName: letsencrypt-staging
  rules:
  - host: #digraph.app
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 80
